"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireAccess, requireAdmin, requireLogin } from "@/lib/guards";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { getWeekStart, REACTION_TYPES } from "@/lib/images";
import { ALLOWED_IMAGE_TYPES, FIELD_REPORT_IMAGE_BUCKET, MAX_UPLOAD_BYTES, PROFILE_AVATAR_BUCKET, storagePublicUrl } from "@/lib/storage";

function value(formData: FormData, key: string) { return String(formData.get(key) || "").trim(); }
function values(formData: FormData, key: string) { return formData.getAll(key).map((item) => String(item).trim()).filter(Boolean); }
function validImageMeta(type: string, size: number) { return ALLOWED_IMAGE_TYPES.includes(type) && size > 0 && size <= MAX_UPLOAD_BYTES; }

export async function signOut() { const supabase = await createServerSupabaseClient(); await supabase.auth.signOut(); redirect("/"); }

export async function submitImage(formData: FormData) {
  const { user } = await requireAccess(); const supabase = await createServerSupabaseClient(); const week = getWeekStart();
  const title=value(formData,"title"), capture_date=value(formData,"capture_date"), country=value(formData,"country"), state_or_province=value(formData,"state_or_province"), gear_settings=value(formData,"gear_settings");
  const image_original_path=value(formData,"image_original_path"), image_mime_type=value(formData,"image_mime_type"), submission_id=value(formData,"submission_id");
  const image_size_bytes=Number(value(formData,"image_size_bytes") || 0), image_width=Number(value(formData,"image_width") || 0) || null, image_height=Number(value(formData,"image_height") || 0) || null;
  if (!title || !image_original_path || !capture_date || !country || !state_or_province || !gear_settings) return { error: "Please complete all required fields and upload an image." };
  if (!validImageMeta(image_mime_type, image_size_bytes)) return { error: "Upload a JPG, PNG, or WebP image up to 30 MB." };
  if (!image_original_path.startsWith(`users/${user.id}/field-reports/${submission_id}/original.`)) return { error: "Image upload path does not match your account." };
  const is_weekly_candidate = formData.get("is_weekly_candidate") === "on";
  if (is_weekly_candidate) { const { count: candidateCount } = await supabase.from("field_reports").select("id",{count:"exact",head:true}).eq("user_id",user.id).eq("iotw_week_start",week).eq("is_iotw_candidate",true).neq("status","removed"); if ((candidateCount || 0)>0) return { error: "You already have an Image of the Week contender this week. You can still submit this as a regular field report." }; }
  const publicUrl = storagePublicUrl(FIELD_REPORT_IMAGE_BUCKET, image_original_path) || "";
  const reportPayload = { id: submission_id || undefined, user_id:user.id, title, capture_date, country, region:state_or_province, specific_location:value(formData,"specific_location_name")||null, gear:gear_settings, story:value(formData,"short_story")||null, went_well:value(formData,"what_went_well")||null, could_have_gone_better:value(formData,"what_could_have_gone_better")||null, image_original_path, image_bucket:FIELD_REPORT_IMAGE_BUCKET, image_width, image_height, image_size_bytes, is_iotw_candidate:is_weekly_candidate, iotw_week_start:is_weekly_candidate ? week : null, status:"published" };
  const { data: report, error: reportError } = await supabase.from("field_reports").insert(reportPayload).select("id").single();
  if (reportError) return { error: reportError.message };
  const { data, error } = await supabase.from("guild_images").insert({ user_id:user.id, title, image_url:publicUrl, image_source:"supabase_storage", image_bucket:FIELD_REPORT_IMAGE_BUCKET, image_original_path, image_width, image_height, image_size_bytes, display_image_path:image_original_path, detail_image_path:image_original_path, capture_date, country, state_or_province, specific_location_name:value(formData,"specific_location_name")||null, gear_settings, short_story:value(formData,"short_story")||null, what_went_well:value(formData,"what_went_well")||null, what_could_have_gone_better:value(formData,"what_could_have_gone_better")||null, is_weekly_candidate, week_starts_on:week, status:"published" }).select("id").single();
  if (error) return { error: error.message };
  await supabase.from("field_reports").update({ guild_image_id: data.id }).eq("id", report.id).eq("user_id", user.id);
  const achievementIds = values(formData, "achievement_ids");
  if (achievementIds.length) {
    await supabase.from("field_report_achievement_claims").insert(achievementIds.map((achievement_id) => ({ field_report_id: report.id, user_id: user.id, achievement_id, status: "auto_awarded_pending_review" })));
    await supabase.from("user_achievements").upsert(achievementIds.map((achievement_id) => ({ user_id: user.id, achievement_id, earned_at: new Date().toISOString(), source_submission_id: data.id, source_field_report_id: report.id, status: "auto_awarded_pending_review", metadata: { source: "field_report_claim" } })), { onConflict: "user_id,achievement_id" });
  }
  revalidatePath("/feed"); revalidatePath("/profile"); redirect(`/images/${data.id}`);
}

export async function addComment(formData: FormData) { const { user } = await requireAccess(); const supabase=await createServerSupabaseClient(); const image_id=value(formData,"image_id"), body=value(formData,"body"); if(!body) return; await supabase.from("image_comments").insert({image_id,user_id:user.id,body}); revalidatePath(`/images/${image_id}`); }
export async function toggleReaction(formData: FormData) { const { user } = await requireAccess(); const supabase=await createServerSupabaseClient(); const image_id=value(formData,"image_id"), reaction_type=value(formData,"reaction_type"); if(!REACTION_TYPES.some(([t])=>t===reaction_type)) return; const {data}=await supabase.from("image_reactions").select("id").eq("image_id",image_id).eq("user_id",user.id).eq("reaction_type",reaction_type).maybeSingle(); if(data) await supabase.from("image_reactions").delete().eq("id",data.id); else await supabase.from("image_reactions").insert({image_id,user_id:user.id,reaction_type}); revalidatePath(`/images/${image_id}`); revalidatePath("/feed"); }
export async function toggleWeeklyCandidate(formData: FormData) { const { user } = await requireAccess(); const supabase=await createServerSupabaseClient(); const image_id=value(formData,"image_id"), week=value(formData,"week_starts_on"), next=value(formData,"next")==="true"; if(next){ const { count }=await supabase.from("guild_images").select("id",{count:"exact",head:true}).eq("user_id",user.id).eq("week_starts_on",week).eq("is_weekly_candidate",true).is("deleted_at",null).neq("id",image_id); if((count||0)>0) return; } await supabase.from("guild_images").update({is_weekly_candidate:next}).eq("id",image_id).eq("user_id",user.id); revalidatePath(`/images/${image_id}`); revalidatePath("/feed"); }
export async function updateProfileLocation(formData: FormData) { const { user }=await requireLogin(); const supabase=await createServerSupabaseClient(); const avatar_path=value(formData,"avatar_path")||null; await supabase.from("profiles").update({display_name:value(formData,"display_name")||null,avatar_path,avatar_url:avatar_path ? storagePublicUrl(PROFILE_AVATAR_BUCKET, avatar_path) : undefined,country:value(formData,"country")||null,region:value(formData,"state_or_province")||null,state_or_province:value(formData,"state_or_province")||null,specific_location:value(formData,"specific_location_name")||null,specific_location_name:value(formData,"specific_location_name")||null}).eq("id",user.id); revalidatePath("/profile"); }
export async function adminImageAction(formData: FormData) { const { user }=await requireAdmin(); const supabase=await createServerSupabaseClient(); const image_id=value(formData,"image_id"), action=value(formData,"action"); const reason=value(formData,"moderation_reason")||null; const patch:any={moderation_reason:reason}; if(action==="hide") Object.assign(patch,{hidden_at:new Date().toISOString(),hidden_by:user.id,moderation_status:"hidden",status:"hidden"}); if(action==="unhide") Object.assign(patch,{hidden_at:null,hidden_by:null,moderation_status:"visible",status:"published"}); if(action==="delete") Object.assign(patch,{deleted_at:new Date().toISOString(),deleted_by:user.id,moderation_status:"deleted",status:"removed"}); if(action==="blur") Object.assign(patch,{moderation_blur_required:true,moderation_status:"blurred"}); if(action==="unblur") Object.assign(patch,{moderation_blur_required:false,moderation_status:"visible"}); if(action==="review") Object.assign(patch,{moderation_reviewed_by:user.id,moderation_reviewed_at:new Date().toISOString()}); await supabase.from("guild_images").update(patch).eq("id",image_id); revalidatePath("/admin/images"); }
