export type IotwEntry={field_report_id:string;title:string;image_url:string|null;photographer_name:string;user_id:string;capture_date?:string|null;location?:string|null};
export type IotwVote={first_place_field_report_id:string|null;second_place_field_report_id:string|null;third_place_field_report_id:string|null};
const TZ='America/Denver';
function parts(date:Date){const f=new Intl.DateTimeFormat('en-US',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23',weekday:'short'});return Object.fromEntries(f.formatToParts(date).filter(p=>p.type!=='literal').map(p=>[p.type,p.value]));}
function mtToUtc(y:number,m:number,d:number,h=12){let utc=new Date(Date.UTC(y,m-1,d,h,0,0));for(let i=0;i<3;i++){const p=parts(utc);const as=Date.UTC(+p.year,+p.month-1,+p.day,+p.hour,+p.minute,+p.second);utc=new Date(utc.getTime()-(as-utc.getTime()));}return utc;}
export function getIotwPeriod(now=new Date()){const p=parts(now);const localMid=mtToUtc(+p.year,+p.month,+p.day,0);const dow=new Date(Date.UTC(+p.year,+p.month-1,+p.day)).getUTCDay();const thisSundayLocalDay=new Date(Date.UTC(+p.year,+p.month-1,+p.day-dow));const open=mtToUtc(thisSundayLocalDay.getUTCFullYear(),thisSundayLocalDay.getUTCMonth()+1,thisSundayLocalDay.getUTCDate(),12);const start=now>=open?open:mtToUtc(thisSundayLocalDay.getUTCFullYear(),thisSundayLocalDay.getUTCMonth()+1,thisSundayLocalDay.getUTCDate()-7,12);const end=mtToUtc(start.getUTCFullYear(),start.getUTCMonth()+1,start.getUTCDate()+7,12);return{period_start:start.toISOString(),period_end:end.toISOString(),submission_cutoff:start.toISOString(),voting_opens_at:start.toISOString(),voting_closes_at:end.toISOString(),status:now<start?'upcoming':now<end?'voting_open':'voting_closed'};}
export function getIotwTargetPeriod(now=new Date()){const active=getIotwPeriod(now);const n=now.toISOString();if(n<active.submission_cutoff)return active;const start=new Date(active.period_end);const end=mtToUtc(start.getUTCFullYear(),start.getUTCMonth()+1,start.getUTCDate()+7,12);return{period_start:start.toISOString(),period_end:end.toISOString(),submission_cutoff:start.toISOString(),voting_opens_at:start.toISOString(),voting_closes_at:end.toISOString(),status:'upcoming'};}
export function formatMountainDeadline(iso:string){return new Intl.DateTimeFormat('en-US',{timeZone:TZ,weekday:'long',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'}).format(new Date(iso));}
export function calculateIotwResults(entries:IotwEntry[],votes:IotwVote[]){const map=new Map(entries.map(e=>[e.field_report_id,{...e,total_points:0,first_place_count:0,second_place_count:0,third_place_count:0,total_ballots:0}]));for(const v of votes){const seen=new Set<string>();[[v.first_place_field_report_id,3,'first_place_count'],[v.second_place_field_report_id,2,'second_place_count'],[v.third_place_field_report_id,1,'third_place_count']].forEach(([id,pts,key])=>{if(typeof id==='string'&&!seen.has(id)){const r=map.get(id);if(r){(r as any).total_points+=pts;(r as any)[key as string]+=1;seen.add(id);}}});for(const id of seen){const r=map.get(id);if(r)r.total_ballots+=1;}}return [...map.values()].sort((a,b)=>b.total_points-a.total_points||b.first_place_count-a.first_place_count||b.total_ballots-a.total_ballots||b.second_place_count-a.second_place_count||a.title.localeCompare(b.title)).map((r,i)=>({...r,rank:i+1}));}
