create table if not exists public.iotw_ballots (
  id uuid primary key default gen_random_uuid(), period_start timestamptz not null, period_end timestamptz not null, submission_cutoff timestamptz not null, voting_opens_at timestamptz not null, voting_closes_at timestamptz not null,
  status text not null default 'upcoming' check (status in ('upcoming','voting_open','voting_closed','finalized')),
  winner_field_report_id uuid references public.field_reports(id) on delete set null, second_place_field_report_id uuid references public.field_reports(id) on delete set null, third_place_field_report_id uuid references public.field_reports(id) on delete set null, photog_phavorite_field_report_id uuid references public.field_reports(id) on delete set null,
  admin_notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(period_start)
);
create table if not exists public.iotw_ballot_entries (id uuid primary key default gen_random_uuid(), ballot_id uuid not null references public.iotw_ballots(id) on delete cascade, field_report_id uuid not null references public.field_reports(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, submitted_at timestamptz not null default now(), created_at timestamptz not null default now(), unique(ballot_id,user_id), unique(ballot_id,field_report_id));
create table if not exists public.iotw_votes (id uuid primary key default gen_random_uuid(), ballot_id uuid not null references public.iotw_ballots(id) on delete cascade, voter_user_id uuid not null references auth.users(id) on delete cascade, first_place_field_report_id uuid not null references public.field_reports(id) on delete cascade, second_place_field_report_id uuid references public.field_reports(id) on delete cascade, third_place_field_report_id uuid references public.field_reports(id) on delete cascade, submitted_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(ballot_id,voter_user_id), check (first_place_field_report_id is distinct from second_place_field_report_id), check (first_place_field_report_id is distinct from third_place_field_report_id), check (second_place_field_report_id is null or second_place_field_report_id is distinct from third_place_field_report_id));
drop trigger if exists iotw_ballots_set_updated_at on public.iotw_ballots; create trigger iotw_ballots_set_updated_at before update on public.iotw_ballots for each row execute function public.set_updated_at();
drop trigger if exists iotw_votes_set_updated_at on public.iotw_votes; create trigger iotw_votes_set_updated_at before update on public.iotw_votes for each row execute function public.set_updated_at();
alter table public.iotw_ballots enable row level security; alter table public.iotw_ballot_entries enable row level security; alter table public.iotw_votes enable row level security;
create policy "Members read IOTW ballots" on public.iotw_ballots for select using (public.can_view_guild() or public.is_admin()); create policy "Admins manage IOTW ballots" on public.iotw_ballots for all using (public.is_admin()) with check (public.is_admin());
create policy "Members read IOTW entries" on public.iotw_ballot_entries for select using (public.can_view_guild() or public.is_admin()); create policy "Members enter own reports" on public.iotw_ballot_entries for insert with check (user_id=auth.uid() and exists(select 1 from public.field_reports fr where fr.id=field_report_id and fr.user_id=auth.uid())); create policy "Admins manage IOTW entries" on public.iotw_ballot_entries for all using (public.is_admin()) with check (public.is_admin());
create policy "Members read own IOTW votes" on public.iotw_votes for select using (voter_user_id=auth.uid() or public.is_admin()); create policy "Members insert own open IOTW votes" on public.iotw_votes for insert with check (voter_user_id=auth.uid() and exists(select 1 from public.iotw_ballots b where b.id=ballot_id and b.status='voting_open' and now()>=b.voting_opens_at and now()<b.voting_closes_at)); create policy "Members update own open IOTW votes" on public.iotw_votes for update using (voter_user_id=auth.uid()) with check (voter_user_id=auth.uid() and exists(select 1 from public.iotw_ballots b where b.id=ballot_id and b.status='voting_open' and now()<b.voting_closes_at)); create policy "Admins read IOTW votes" on public.iotw_votes for select using (public.is_admin());
grant select on public.iotw_ballots, public.iotw_ballot_entries to authenticated; grant select,insert,update on public.iotw_votes to authenticated; grant insert on public.iotw_ballot_entries to authenticated;
